### ISSUE TITLE
Change repo name and add description hyperlink to domain

### ISSUE THREAD

**Issue by ab12gu** [geluso/206bikepolo.com#2]
Can you change the repo name to just 206bikepolo. It becomes kinda annoying to have to repo-name have the extension, because it doesn't link to the domain when clicked.... just goes back to the repository on github...

Also, I can't edit description, but I generally put the domain hyperlink in description for easy nav. Can you do that? Just go to settings and click description and add https://206bikepolo.com, I think you can just double click about section on repo actually if you are the host...

**Comment by geluso** [comment]
Repo is named `206bikepolo.com` to match a pattern on the server. The server expects websites to exist in folders with their domain name. This makes it easy for me to clone and saves me exactly one `mv 206bikepolo 206bikepolo.com`.

Small thing, but no I don't feel compelled to change it.

There's a link to the website in the README. Also the website is self evident. Type it in!

Strange, I don't see "description" in Settings. 

![Screenshot 2024-06-07 at 1 06 52 PM](https://github.com/geluso/206bikepolo.com/assets/510868/3cd50fed-208a-47cf-9867-a6c780ff6e9e)

**Comment by ab12gu** [comment]
yeah... i guess u don't need to change the domain #...

![image](https://github.com/geluso/206bikepolo.com/assets/24667333/f60d9096-c15b-4351-808d-0ce26525e01f)

**Comment by geluso** [comment]
Got it, thanks!
